# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.7/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.7/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hujingbo99/new_hnswlib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hujingbo99/new_hnswlib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python3.7/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hujingbo99/new_hnswlib/CMakeFiles /home/hujingbo99/new_hnswlib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hujingbo99/new_hnswlib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_updates

# Build rule for target.
test_updates: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_updates
.PHONY : test_updates

# fast build rule for target.
test_updates/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_updates.dir/build.make CMakeFiles/test_updates.dir/build
.PHONY : test_updates/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named sift_test

# Build rule for target.
sift_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sift_test
.PHONY : sift_test

# fast build rule for target.
sift_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sift_test.dir/build.make CMakeFiles/sift_test.dir/build
.PHONY : sift_test/fast

examples/updates_test.o: examples/updates_test.cpp.o

.PHONY : examples/updates_test.o

# target to build an object file
examples/updates_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_updates.dir/build.make CMakeFiles/test_updates.dir/examples/updates_test.cpp.o
.PHONY : examples/updates_test.cpp.o

examples/updates_test.i: examples/updates_test.cpp.i

.PHONY : examples/updates_test.i

# target to preprocess a source file
examples/updates_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_updates.dir/build.make CMakeFiles/test_updates.dir/examples/updates_test.cpp.i
.PHONY : examples/updates_test.cpp.i

examples/updates_test.s: examples/updates_test.cpp.s

.PHONY : examples/updates_test.s

# target to generate assembly for a file
examples/updates_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_updates.dir/build.make CMakeFiles/test_updates.dir/examples/updates_test.cpp.s
.PHONY : examples/updates_test.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

sift_1b.o: sift_1b.cpp.o

.PHONY : sift_1b.o

# target to build an object file
sift_1b.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sift_test.dir/build.make CMakeFiles/sift_test.dir/sift_1b.cpp.o
.PHONY : sift_1b.cpp.o

sift_1b.i: sift_1b.cpp.i

.PHONY : sift_1b.i

# target to preprocess a source file
sift_1b.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sift_test.dir/build.make CMakeFiles/sift_test.dir/sift_1b.cpp.i
.PHONY : sift_1b.cpp.i

sift_1b.s: sift_1b.cpp.s

.PHONY : sift_1b.s

# target to generate assembly for a file
sift_1b.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sift_test.dir/build.make CMakeFiles/sift_test.dir/sift_1b.cpp.s
.PHONY : sift_1b.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... sift_test"
	@echo "... test_updates"
	@echo "... examples/updates_test.o"
	@echo "... examples/updates_test.i"
	@echo "... examples/updates_test.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sift_1b.o"
	@echo "... sift_1b.i"
	@echo "... sift_1b.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

